### ISSUE TITLE
Вопрос по поводу настроек редактора

### ISSUE THREAD

**Issue by prozion** [aleksandrchusovitin/frontend-project-lvl2#1]
Просто интересно, в каком редакторе кода используется файл [.editorconfig](https://github.com/aleksandrchusovitin/frontend-project-lvl2/blob/main/.editorconfig)?

**Comment by aleksandrchusovitin** [comment]
Я использую **VScode**, для него есть отдельный плагин, в **WebStorm** _editorconfig_ встроен по умолчанию, насколько я знаю. А так ,практически в любом современном редакторе он либо предустановлен, либо устанавливается в виде плагина :)
[Предустановлен](https://editorconfig.org/#pre-installed)
[В виде плагина](https://editorconfig.org/#download)

**Comment by prozion** [comment]
А, теперь разобрался. Этот конфигурационный файл используется чтобы у всех людей в команде, использующих каждый свой IDE, код отображался одинаково. Особенно это актуально насчет вопроса табы vs пробелы, и сколько пробелов в табе/отступе.

**Comment by aleksandrchusovitin** [comment]
Да, точнее и не опишешь :)
